---
title: "Suicide Rates in 1970"
author: "Alexander Kahanek"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(cowplot)
```


# loading data


```{r}
raw <- read.csv('suicides1970.csv') %>% 
  rename(
    "month" = Month
    ,"nSuicides" = Number
    ,"nDays" = Days
  ) %>% 
  mutate(
    season = ifelse(month < 3 | month == 12, "winter",
                    ifelse(month < 6, "spring",
                           ifelse(month < 9, "summer", "autumn")))
    ,suicides_per_day = nSuicides / nDays
  )


raw %>% head(20)
```


# boxplot of suicides per month


```{r}
ggplot(raw) + 
  geom_boxplot(aes(x=nSuicides)) + 
  labs(title = "The distribution of the number of suicides, per month in 1970"
       ,x = "number of suicides, per month"
       ,y = "") + 
  theme(axis.title.y=element_blank()
        ,axis.text.y=element_blank()
        ,axis.ticks.y=element_blank())
```


# plot of empirical cumulative density for suicides, per month


```{r}
ecdf(raw$nSuicides) %>% 
  plot(main = "Empirical Cumulative Distribution of the number of suicides in 1970"
       ,xlab = "Number of suicides, per month"
       ,ylab = "Cumulative probability")
```


# Suicides per day comparison

```{r}
p1 <- ggplot(raw) +
  geom_bar(aes(x=as.factor(month), y=nSuicides), stat = "identity") +
  labs(title = "The number of suicides, per month"
       ,x = "Index of Month"
       ,y = "Number of suicides, per month")

p2 <- ggplot(raw) +
  geom_bar(aes(x=as.factor(month), y=suicides_per_day), stat = "identity") +
  labs(title = "The number of suicides, per day for each month"
       ,x = "Index of Month"
       ,y = "Number of suicides, per day")

plot_grid(p1, p2)
```



# goodness-of-fit test (pearsons chi-sq) for modeled months

```{r}
total_spd <- 772.1843 # the total sum of the number of suicides per day

probs <- raw %>% # the probability of a suicide being in a month
  group_by(month) %>%
  summarise (
    p = sum(suicides_per_day) / total_spd
  ) %>%
  select(p) %>%
  unlist() %>%
  as.numeric()

number_of_experiments <- 1 # how many times to draw K samples
number_of_samples <- 100000 # the amount of samples per experiment

multinomial_model_obs <- rmultinom(n = number_of_experiments, size = number_of_samples, prob = probs)

model <- multinomial_model_obs %>% # find observations and probabilities of our model
  as.data.frame() %>% 
  rename("obs" = V1) %>% 
  mutate(
    month = 1:n()
    ,p = obs / number_of_samples
  )

Dchisq.test(model$obs, p = raw$nDays/365)
# chisq.test(model$obs, p = c(rep(1/12, 12)))
```

# goodness-of-fit test (pearsons chi-sq) for modeled seasons

```{r}
probs_seasons <- raw %>% # the probability of a suicide being in a season
  group_by(season) %>%
  summarise(
    p = sum(suicides_per_day) / total_spd
  ) %>% 
  select(p) %>%
  unlist() %>%
  as.numeric()

number_of_experiments <- 1 # how many times to draw K samples
number_of_samples <- 100000 # the amount of samples per experiment

multinomial_model_obs <- rmultinom(n = number_of_experiments, size = number_of_samples, prob = probs_seasons)

model_seasons <- multinomial_model_obs %>% # find observations and probabilities of our model
  as.data.frame() %>%
  rename("obs" = V1) %>%
  mutate(
    season = 1:n()
    ,p = obs / number_of_samples
  )

# constant = raw %>% group_by(season) %>% summarise(c= sum(nDays)/365) %>% select(c)
chisq.test(model_seasons$obs, p = c(0.249, 0.252, 0.252, 0.247))
```